//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RtoTools.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RtoTools.Common.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Faction.
        /// </summary>
        public static string AsFaction {
            get {
                return ResourceManager.GetString("AsFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Builder.
        /// </summary>
        public static string ContractBuilder {
            get {
                return ResourceManager.GetString("ContractBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Contracts ({0}).
        /// </summary>
        public static string CurrentContracts {
            get {
                return ResourceManager.GetString("CurrentContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Owner.
        /// </summary>
        public static string CurrentOwner {
            get {
                return ResourceManager.GetString("CurrentOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deniable Asset Contracts will never be shown.
        /// </summary>
        public static string DeniableAssetWarning {
            get {
                return ResourceManager.GetString("DeniableAssetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated {0}.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load File.
        /// </summary>
        public static string LoadFile {
            get {
                return ResourceManager.GetString("LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Faction Control.
        /// </summary>
        public static string OtherFactionControl {
            get {
                return ResourceManager.GetString("OtherFactionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Control.
        /// </summary>
        public static string OwnerControl {
            get {
                return ResourceManager.GetString("OwnerControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided Support.
        /// </summary>
        public static string ProvidedSupport {
            get {
                return ResourceManager.GetString("ProvidedSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait ({0}s).
        /// </summary>
        public static string RefreshDataCooldown {
            get {
                return ResourceManager.GetString("RefreshDataCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Data.
        /// </summary>
        public static string RefreshDataReady {
            get {
                return ResourceManager.GetString("RefreshDataReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Logs.
        /// </summary>
        public static string SaveLogs {
            get {
                return ResourceManager.GetString("SaveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select).
        /// </summary>
        public static string SelectOption {
            get {
                return ResourceManager.GetString("SelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Name.
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Control (100 - 500).
        /// </summary>
        public static string TargetControl {
            get {
                return ResourceManager.GetString("TargetControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Faction.
        /// </summary>
        public static string TargetFaction {
            get {
                return ResourceManager.GetString("TargetFaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target System.
        /// </summary>
        public static string TargetSystem {
            get {
                return ResourceManager.GetString("TargetSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Faction.
        /// </summary>
        public static string YourFaction {
            get {
                return ResourceManager.GetString("YourFaction", resourceCulture);
            }
        }
    }
}
